invoker.goals=clean licenses:insert-versions -X -Dlicense.includeOptionalDependencies=false -DlicensesConfigFile=licenses.xml -Dlicense.shadedArtifactsFile=shaded.xml
invoker.failureBehavior=fail-fast